/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelayakanmustahiq.view;

import kelayakanmustahiq.entities.Mustahiq;
import kelayakanmustahiq.function.FunctionMustahiq;
import kelayakanmustahiq.fuzzy.MembershipFunction;
import kelayakanmustahiq.fuzzy.Tsukamoto;
import kelayakanmustahiq.model.MustahiqModel;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import kelayakanmustahiq.report.Reports;

/**
 *
 * @author Hadyan Ahmad
 */
public class PanelKelayakan extends javax.swing.JPanel {

    private final MustahiqModel cmm = new MustahiqModel();

    /**
     * Creates new form PanelMustahiq
     */
    public PanelKelayakan() {
        initComponents();
        FillData();
    }

    private String number(int x) {
        String num = "Rp. " + NumberFormat.getIntegerInstance().format(x) + ",-";
        return num;
    }

    private String keterangan(float x) {
        String keterangan;
        if (x > 60) {
            keterangan = "Layak";
        } else {
            keterangan = "Tidak Layak";
        }
        return keterangan;
    }

    private Float decimal(float derajatInput) {
        DecimalFormat decimal = new DecimalFormat();
        decimal.setMaximumFractionDigits(2);
        String derajatProccess = decimal.format(derajatInput);
        float derajatOutput = Float.valueOf(derajatProccess);
        return derajatOutput;
    }

    private void FillData() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("#");
        dtm.addColumn("Nama Mustahiq");
        dtm.addColumn("Tanggungan");
        dtm.addColumn("Kualitas Tempat Tinggal");
        dtm.addColumn("Pendapatan");
        dtm.addColumn("Attitude");
        dtm.addColumn("Kelayakan");
        dtm.addColumn("Keterangan");

        ArrayList list = new ArrayList();
        for (Mustahiq cm : this.cmm.findAll()) {
            list.add(cm.getIdMustahiq());
        }

        for (Mustahiq cm : this.cmm.findAll()) {
            int x = list.indexOf(cm.getIdMustahiq()) + 1;
            dtm.addRow(new Object[]{x, cm.getNamaMustahiq(), cm.getJumlahTanggungan(), cm.getKualitasTempattinggal(),
                number(cm.getJumlahPendapatan()), cm.getAttitude(), cm.getKelayakan(), cm.getStatus()});
        }
        this.tblKelayakan.setModel(dtm);
        tblKelayakan.setRowSorter(new TableRowSorter(dtm));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        lblHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKelayakan = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        jButton1.setText("jButton1");

        panelImage1.setForeground(new java.awt.Color(0, 0, 0));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/mosque_yellow.jpg"))); // NOI18N

        lblHeader.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 0, 0));
        lblHeader.setText("LIST KELAYAKAN MUSTAHIQ");

        tblKelayakan.setBackground(new java.awt.Color(255, 255, 153));
        tblKelayakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKelayakan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblKelayakan.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tblKelayakan);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/repeat_24px.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/list_24px.png"))); // NOI18N
        btnReport.setText("Report");
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh)))
                .addContainerGap())
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader)
                    .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefresh)
                        .addComponent(btnReport)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:

        MembershipFunction mf = new MembershipFunction();
        Mustahiq mustahiq = new Mustahiq();
        Tsukamoto tsukamoto = new Tsukamoto();
        FunctionMustahiq fm = new FunctionMustahiq();
        try {
            for (Mustahiq m : this.cmm.findAll()) {
                int id = m.getIdMustahiq();
                m = this.cmm.find(id);

                mustahiq.setIdMustahiq(id);
                mustahiq.setNamaMustahiq(fm.namaMustahiq(id));
                mustahiq.setAlamat(fm.alamat(id));
                mustahiq.setJumlahTanggungan(fm.jumlahTanggungan(id));
                mustahiq.setKualitasTempattinggal(fm.tempatTinggal(id));
                mustahiq.setJumlahPendapatan(fm.jumlahPendapatan(id));
                mustahiq.setAttitude(fm.attitude(id));
                mustahiq.setKelayakan(decimal(tsukamoto.z(id)));
                mustahiq.setStatus(keterangan(tsukamoto.z(id)));
                this.cmm.update(mustahiq);
            }
        } catch (Exception e) {
        }
        FillData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.printReport();
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private javax.swing.JLabel lblHeader;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTable tblKelayakan;
    // End of variables declaration//GEN-END:variables
}
