/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelayakanmustahiq;

import kelayakanmustahiq.view.DialogAbout;
import kelayakanmustahiq.view.DialogAttitude;
import kelayakanmustahiq.view.DialogTempatTinggal;
import kelayakanmustahiq.view.DialogPendapatan;
import kelayakanmustahiq.view.DialogKelayakanSedekah;
import kelayakanmustahiq.view.DialogStudent;
import kelayakanmustahiq.view.DialogTanggungan;
import kelayakanmustahiq.view.PanelMustahiq;
import kelayakanmustahiq.view.PanelPerhitungan;
import kelayakanmustahiq.view.PanelKelayakan;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import kelayakanmustahiq.report.Reports;

/**
 *
 * @author Hadyan Ahmad
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
//        autoHide();
        setIcon();
        clearPanel();
    }

    private void autoHide() {
        this.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                jToolBar1.setVisible(e.getX() < 35);

            }
        });
    }
    
    private void setIcon() {
        URL iconURL = getClass().getResource("/kelayakanmustahiq/resource/calculator-1_55px.png");
// iconURL is null when not found
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
    }

    private void panelParent(JPanel panel) {
        PanelParent.removeAll();
        PanelParent.add(panel);
        PanelParent.repaint();
        PanelParent.revalidate();
    }

    private void clearPanel() {
        PanelParent.removeAll();
        PanelParent.repaint();
        PanelParent.revalidate();
    }
    
    private void close() {
        int result = JOptionPane.showConfirmDialog(null, "Apakah yakin Anda akan keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    protected void addImpl(Component comp, Object constraints, int index) {
        super.addImpl(comp, constraints, index);
        if (comp instanceof JButton) {
            ((JButton) comp).setContentAreaFilled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        btnMustahiq = new javax.swing.JButton();
        btnPerhitungan = new javax.swing.JButton();
        btnSedekah = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        PanelParent = new org.edisoncor.gui.panel.PanelImage();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI PENENTU KELAYAKAN PENERIMA SEDEKAH");

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setForeground(new java.awt.Color(0, 0, 0));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/home_55px.png"))); // NOI18N
        btnHome.setText("HOME");
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHome);

        btnMustahiq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/user-3_55px.png"))); // NOI18N
        btnMustahiq.setText("MUSTAHIQ");
        btnMustahiq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMustahiq.setFocusable(false);
        btnMustahiq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMustahiq.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMustahiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMustahiqActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMustahiq);

        btnPerhitungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/calculator_55px.png"))); // NOI18N
        btnPerhitungan.setText("HITUNG");
        btnPerhitungan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerhitungan.setFocusable(false);
        btnPerhitungan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPerhitungan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPerhitungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerhitunganActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPerhitungan);

        btnSedekah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/money_55px.png"))); // NOI18N
        btnSedekah.setText("KELAYAKAN");
        btnSedekah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSedekah.setFocusable(false);
        btnSedekah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSedekah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSedekah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSedekahActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSedekah);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/exit-1_55px.png"))); // NOI18N
        btnExit.setText("EXIT");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        PanelParent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/mosque_blue.jpg"))); // NOI18N
        PanelParent.setLayout(new java.awt.CardLayout());

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_HOME, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/home_24px.png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/add-3_24px.png"))); // NOI18N
        jMenu4.setText("Add");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/user-3_24px.png"))); // NOI18N
        jMenuItem2.setText("Mustahiq");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu1.add(jMenu4);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/list_24px.png"))); // NOI18N
        jMenuItem14.setText("Report");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/exit-1_24px.png"))); // NOI18N
        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Domain");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/users_24px.png"))); // NOI18N
        jMenuItem9.setText("Tanggungan");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/house_24px.png"))); // NOI18N
        jMenuItem10.setText("Tempat Tinggal");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/notes_24px.png"))); // NOI18N
        jMenuItem11.setText("Pendapatan");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/user_24px.png"))); // NOI18N
        jMenuItem12.setText("Attitude");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);
        jMenu5.add(jSeparator1);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/money_24px.png"))); // NOI18N
        jMenuItem13.setText("Kelayakan");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("List");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/user-3_24px.png"))); // NOI18N
        jMenuItem3.setText("Mustahiq");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/calculator_24px.png"))); // NOI18N
        jMenuItem4.setText("Perhitungan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/money_24px.png"))); // NOI18N
        jMenuItem8.setText("Kelayakan");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/warning_24px.png"))); // NOI18N
        jMenuItem6.setText("Tentang Aplikasi");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelayakanmustahiq/resource/id-card-5_24px.png"))); // NOI18N
        jMenuItem7.setText("Student");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .addComponent(PanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btnExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        clearPanel();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        clearPanel();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        PanelMustahiq panelMustahiq = new PanelMustahiq();
        panelParent(panelMustahiq);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnMustahiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMustahiqActionPerformed
        // TODO add your handling code here:
        PanelMustahiq panelMustahiq = new PanelMustahiq();
        panelParent(panelMustahiq);
    }//GEN-LAST:event_btnMustahiqActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        PanelPerhitungan panelPerhitungan = new PanelPerhitungan();
        panelParent(panelPerhitungan);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnPerhitunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerhitunganActionPerformed
        // TODO add your handling code here:
        PanelPerhitungan panelPerhitungan = new PanelPerhitungan();
        panelParent(panelPerhitungan);
    }//GEN-LAST:event_btnPerhitunganActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        PanelKelayakan panelSedekah = new PanelKelayakan();
        panelParent(panelSedekah);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btnSedekahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSedekahActionPerformed
        // TODO add your handling code here:
        PanelKelayakan panelSedekah = new PanelKelayakan();
        panelParent(panelSedekah);
    }//GEN-LAST:event_btnSedekahActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        DialogTanggungan dt = new DialogTanggungan(this, rootPaneCheckingEnabled);
        dt.setLocationRelativeTo(null);
        dt.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        DialogTempatTinggal db = new DialogTempatTinggal(this, rootPaneCheckingEnabled);
        db.setLocationRelativeTo(null);
        db.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        DialogPendapatan dp = new DialogPendapatan(this, rootPaneCheckingEnabled);
        dp.setLocationRelativeTo(null);
        dp.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        DialogAttitude da = new DialogAttitude(this, rootPaneCheckingEnabled);
        da.setLocationRelativeTo(null);
        da.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        DialogKelayakanSedekah ds = new DialogKelayakanSedekah(this, rootPaneCheckingEnabled);
        ds.setLocationRelativeTo(null);
        ds.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        PanelMustahiq panelMustahiq = new PanelMustahiq();
        panelParent(panelMustahiq);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        DialogAbout da = new DialogAbout(this, rootPaneCheckingEnabled);
        da.setLocationRelativeTo(null);
        da.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        DialogStudent ds = new DialogStudent(this, rootPaneCheckingEnabled);
        ds.setLocationRelativeTo(null);
        ds.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.printReport();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage PanelParent;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMustahiq;
    private javax.swing.JButton btnPerhitungan;
    private javax.swing.JButton btnSedekah;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
