package kelayakanmustahiq.entities;
// Generated Feb 24, 2017 6:41:49 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Mustahiq generated by hbm2java
 */
@Entity
@Table(name = "mustahiq",
         catalog = "kelayakanmustahiq"
)
public class Mustahiq implements java.io.Serializable {

    private int idMustahiq;
    private String namaMustahiq;
    private String alamat;
    private Integer jumlahPendapatan;
    private Integer jumlahTanggungan;
    private Integer kualitasTempattinggal;
    private Integer attitude;
    private Float kelayakan;
    private String status;

    public Mustahiq() {
    }

    public Mustahiq(int idMustahiq, String namaMustahiq, String alamat, String status) {
        this.idMustahiq = idMustahiq;
        this.namaMustahiq = namaMustahiq;
        this.alamat = alamat;
        this.status = status;
    }

    public Mustahiq(int idMustahiq, String namaMustahiq, String alamat, Integer jumlahPendapatan, Integer jumlahTanggungan, Integer kualitasTempattinggal, Integer attitude, Float kelayakan, String status) {
        this.idMustahiq = idMustahiq;
        this.namaMustahiq = namaMustahiq;
        this.alamat = alamat;
        this.jumlahPendapatan = jumlahPendapatan;
        this.jumlahTanggungan = jumlahTanggungan;
        this.kualitasTempattinggal = kualitasTempattinggal;
        this.attitude = attitude;
        this.kelayakan = kelayakan;
        this.status = status;
    }

    @Id
    @GenericGenerator(name = "generator", strategy = "increment")
    @GeneratedValue(generator = "generator")

    @Column(name = "id_mustahiq", unique = true, nullable = false)
    public int getIdMustahiq() {
        return this.idMustahiq;
    }

    public void setIdMustahiq(int idMustahiq) {
        this.idMustahiq = idMustahiq;
    }

    @Column(name = "nama_mustahiq", nullable = false, length = 50)
    public String getNamaMustahiq() {
        return this.namaMustahiq;
    }

    public void setNamaMustahiq(String namaMustahiq) {
        this.namaMustahiq = namaMustahiq;
    }

    @Column(name = "alamat", nullable = false, length = 150)
    public String getAlamat() {
        return this.alamat;
    }

    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    @Column(name = "jumlah_pendapatan")
    public Integer getJumlahPendapatan() {
        return this.jumlahPendapatan;
    }

    public void setJumlahPendapatan(Integer jumlahPendapatan) {
        this.jumlahPendapatan = jumlahPendapatan;
    }

    @Column(name = "jumlah_tanggungan")
    public Integer getJumlahTanggungan() {
        return this.jumlahTanggungan;
    }

    public void setJumlahTanggungan(Integer jumlahTanggungan) {
        this.jumlahTanggungan = jumlahTanggungan;
    }

    @Column(name = "kualitas_tempattinggal")
    public Integer getKualitasTempattinggal() {
        return this.kualitasTempattinggal;
    }

    public void setKualitasTempattinggal(Integer kualitasTempattinggal) {
        this.kualitasTempattinggal = kualitasTempattinggal;
    }

    @Column(name = "attitude")
    public Integer getAttitude() {
        return this.attitude;
    }

    public void setAttitude(Integer attitude) {
        this.attitude = attitude;
    }

    @Column(name = "kelayakan", precision = 12, scale = 0)
    public Float getKelayakan() {
        return this.kelayakan;
    }

    public void setKelayakan(Float kelayakan) {
        this.kelayakan = kelayakan;
    }

    @Column(name = "status", nullable = false, length = 15)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
